# Generated by Django 2.1.7 on 2020-05-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_rent_barter_app', '0002_auto_20200507_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalscategories',
            options={'ordering': ['category', 'subcategory']},
        ),
        migrations.RemoveField(
            model_name='proposalscategories',
            name='title',
        ),
        migrations.AddField(
            model_name='proposals',
            name='current_location_str',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='proposalscategories',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proposalscategories',
            name='subcategory',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='current_location_str',
            field=models.CharField(default='', max_length=256),
        ),
    ]
