# Generated by Django 2.1.7 on 2020-05-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_rent_barter_app', '0003_auto_20200515_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='current_location_lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='current_location_long',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
