# Generated by Django 2.1.7 on 2020-05-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_rent_barter_app', '0004_auto_20200515_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location_lat', models.FloatField(blank=True, default=None, null=True)),
                ('current_location_long', models.FloatField(blank=True, default=None, null=True)),
                ('current_location_str', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='proposals',
            name='current_location_str',
        ),
        migrations.RemoveField(
            model_name='proposals',
            name='proposal_location_latitude',
        ),
        migrations.RemoveField(
            model_name='proposals',
            name='proposal_location_longitude',
        ),
        migrations.RemoveField(
            model_name='users',
            name='current_location_lat',
        ),
        migrations.RemoveField(
            model_name='users',
            name='current_location_long',
        ),
        migrations.RemoveField(
            model_name='users',
            name='current_location_str',
        ),
        migrations.AddField(
            model_name='proposals',
            name='location',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='buy_rent_barter_app.Location'),
        ),
        migrations.AddField(
            model_name='users',
            name='location',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='buy_rent_barter_app.Location'),
        ),
    ]
