# Generated by Django 2.1.7 on 2020-05-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_rent_barter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='complain_subject_proposal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_proposal', to='buy_rent_barter_app.Proposals'),
        ),
        migrations.AlterField(
            model_name='complains',
            name='complain_subject_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_user', to='buy_rent_barter_app.Users'),
        ),
        migrations.AlterField(
            model_name='complains',
            name='initiator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_rent_barter_app.Users'),
        ),
    ]
