# Generated by Django 2.1.7 on 2020-05-07 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_rent_barter_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chainexchangeproposalsanswers',
            old_name='answer_deadline_for_next_chain_exchanger',
            new_name='back_deadline_answer',
        ),
        migrations.RemoveField(
            model_name='proposalitemsrequestsanswers',
            name='accepted_time_by_requested_user',
        ),
        migrations.AddField(
            model_name='proposalitemsrequestsanswers',
            name='additional_money_offers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buy_rent_barter_app.AdditionalRequestsOffers'),
        ),
        migrations.AddField(
            model_name='proposalsitemsrequests',
            name='total_accept_approve_answer',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='chainexchangeproposalsanswers',
            name='chain_exchange_block_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buy_rent_barter_app.PossibleChainExchangeProposals'),
        ),
        migrations.AlterField(
            model_name='proposalitemsrequestsanswers',
            name='request_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buy_rent_barter_app.ProposalsItemsRequests'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='available_items',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='total_items',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='proposalsitemsrequests',
            name='additional_money_offers',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='buy_rent_barter_app.AdditionalRequestsOffers'),
        ),
    ]
