# Generated by Django 2.1.7 on 2020-04-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_rent_barter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementsitemsexchangeconditions',
            name='ad_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buy_rent_barter_app.Advertisements'),
        ),
        migrations.AlterField(
            model_name='rentrequestpriceoffers',
            name='rent_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buy_rent_barter_app.RentRequests'),
        ),
    ]
