# Generated by Django 2.1.7 on 2020-05-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_rent_barter_app', '0002_auto_20200517_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complains',
            name='initiator_user',
        ),
        migrations.AddField(
            model_name='complains',
            name='complain_initiator_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiator_user', to='buy_rent_barter_app.Users'),
        ),
    ]
