# Generated by Django 2.1.7 on 2020-04-19 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_rent_barter_app', '0002_auto_20200419_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsItemExchangeRequestsAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_request', models.BooleanField(default=True)),
                ('answer_message', models.CharField(default='please contact me for further info', max_length=1024)),
                ('answer_time', models.DateTimeField(auto_now_add=True)),
                ('answer_watched', models.DateTimeField(default=None)),
                ('approve_deadline', models.DateTimeField(default=None)),
                ('approve_accepted_time', models.DateTimeField(default=None)),
                ('rent_approve', models.DateTimeField(default=None)),
                ('suggested_items_info_hashcode', models.CharField(default='', max_length=77)),
            ],
        ),
        migrations.RemoveField(
            model_name='adsitemexchangerequestanswer',
            name='rent_request_id',
        ),
        migrations.RenameField(
            model_name='advertisements',
            old_name='ad_content_hashcode',
            new_name='ad_item_description_content_hashcode',
        ),
        migrations.RenameField(
            model_name='possiblechainexchange',
            old_name='previous_wish_items_chain_hashcode',
            new_name='previous_suggested_items_info_hashcode',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_show_user_profile_for_all',
            new_name='show_user_profile_for_all',
        ),
        migrations.AddField(
            model_name='buyrequests',
            name='buy_proposal_hashcode',
            field=models.CharField(default='', max_length=77),
        ),
        migrations.AddField(
            model_name='exchangerequests',
            name='requested_items_info_hashcode',
            field=models.CharField(default='', max_length=77),
        ),
        migrations.AddField(
            model_name='rentrequests',
            name='requested_items_info_hashcode',
            field=models.CharField(default='', max_length=77),
        ),
        migrations.AddField(
            model_name='users',
            name='user_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='complainanswers',
            name='sanction',
            field=models.CharField(choices=[('BA', 'BLOCK ACCOUNT'), ('BSC', 'BLOCK SPECIFIED CONTENT'), ('BADSC', 'BLOCK ACCOUNT AND BLOCK SPECIFIED CONTENT'), ('NS', 'NO SANCTIONS'), ('BC', 'BAD COMPLAIN')], default='NS', max_length=5),
        ),
        migrations.AlterField(
            model_name='donations',
            name='donation_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='exchangerequests',
            name='requested_ad_items',
            field=models.ManyToManyField(related_name='desired_items_for_exchange', to='buy_rent_barter_app.PossibleExchangeItems'),
        ),
        migrations.DeleteModel(
            name='AdsItemExchangeRequestAnswer',
        ),
        migrations.AddField(
            model_name='adsitemexchangerequestsanswers',
            name='rent_request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_rent_barter_app.ExchangeRequests'),
        ),
    ]
