# Generated by Django 2.1.7 on 2020-05-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_rent_barter_app', '0002_auto_20200525_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='blocked_deadline',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
