# Generated by Django 2.1.7 on 2020-05-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_rent_barter_app', '0003_users_blocked_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessages',
            options={'ordering': ['-time_send']},
        ),
    ]
